In [1]:
# Import the dependencies
import pandas as pd
import numpy as np

In [2]:
# Store the CSVs in dataFrames
government_regulation_df = pd.read_csv("Resources/raw/OxCGRT_latest(Aug31,2020).csv")
covid_stats_df = pd.read_csv("Resources/raw/owid-covid-data(Aug31,2020).csv")

C:\Users\twin_\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

### Inspect and Clean: government_regulation_df

In [3]:
# Review initial DataFrame
government_regulation_df.head()

,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,20200101,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,20200102,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,20200103,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,20200104,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,20200105,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# Review data types to ensure appropriateness
government_regulation_df.dtypes

CountryName                               object
CountryCode                               object
RegionName                                object
RegionCode                                object
Date                                       int64
C1_School closing                        float64
C1_Flag                                  float64
C2_Workplace closing                     float64
C2_Flag                                  float64
C3_Cancel public events                  float64
C3_Flag                                  float64
C4_Restrictions on gatherings            float64
C4_Flag                                  float64
C5_Close public transport                float64
C5_Flag                                  float64
C6_Stay at home requirements             float64
C6_Flag                                  float64
C7_Restrictions on internal movement     float64
C7_Flag                                  float64
C8_International travel controls         float64
E1_Income support                        float64
E1_Flag                                  float64
E2_Debt/contract relief                  float64
E3_Fiscal measures                       float64
E4_International support                 float64
H1_Public information campaigns          float64
H1_Flag                                  float64
H2_Testing policy                        float64
H3_Contact tracing                       float64
H4_Emergency investment in healthcare    float64
H5_Investment in vaccines                float64
M1_Wildcard                              float64
ConfirmedCases                           float64
ConfirmedDeaths                          float64
StringencyIndex                          float64
StringencyIndexForDisplay                float64
StringencyLegacyIndex                    float64
StringencyLegacyIndexForDisplay          float64
GovernmentResponseIndex                  float64
GovernmentResponseIndexForDisplay        float64
ContainmentHealthIndex                   float64
ContainmentHealthIndexForDisplay         float64
EconomicSupportIndex                     float64
EconomicSupportIndexForDisplay           float64
dtype: object

In [5]:
# Convert "Date" column to format datetime
government_regulation_df['Date_updated'] = pd.to_datetime(government_regulation_df['Date'].astype(str), format='%Y%m%d')

# Drop old "Date" column
government_regulation_df = government_regulation_df.drop(["Date"], axis=1)

government_regulation_df.head()

,CountryName,CountryCode,RegionName,RegionCode,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,...,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay,Date_updated
0,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
1,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-02
2,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-03
3,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-04
4,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-05

In [6]:
# Re-review data types to ensure appropriateness
government_regulation_df.dtypes

CountryName                                      object
CountryCode                                      object
RegionName                                       object
RegionCode                                       object
C1_School closing                               float64
C1_Flag                                         float64
C2_Workplace closing                            float64
C2_Flag                                         float64
C3_Cancel public events                         float64
C3_Flag                                         float64
C4_Restrictions on gatherings                   float64
C4_Flag                                         float64
C5_Close public transport                       float64
C5_Flag                                         float64
C6_Stay at home requirements                    float64
C6_Flag                                         float64
C7_Restrictions on internal movement            float64
C7_Flag                                         float64
C8_International travel controls                float64
E1_Income support                               float64
E1_Flag                                         float64
E2_Debt/contract relief                         float64
E3_Fiscal measures                              float64
E4_International support                        float64
H1_Public information campaigns                 float64
H1_Flag                                         float64
H2_Testing policy                               float64
H3_Contact tracing                              float64
H4_Emergency investment in healthcare           float64
H5_Investment in vaccines                       float64
M1_Wildcard                                     float64
ConfirmedCases                                  float64
ConfirmedDeaths                                 float64
StringencyIndex                                 float64
StringencyIndexForDisplay                       float64
StringencyLegacyIndex                           float64
StringencyLegacyIndexForDisplay                 float64
GovernmentResponseIndex                         float64
GovernmentResponseIndexForDisplay               float64
ContainmentHealthIndex                          float64
ContainmentHealthIndexForDisplay                float64
EconomicSupportIndex                            float64
EconomicSupportIndexForDisplay                  float64
Date_updated                             datetime64[ns]
dtype: object

In [7]:
# Verify date range - ensure only 2020 dates for analysis
government_regulation_df.groupby("Date_updated")["CountryCode"].nunique()

Date_updated
2020-01-01    185
2020-01-02    185
2020-01-03    185
2020-01-04    185
2020-01-05    185
             ...
2020-08-27    185
2020-08-28    185
2020-08-29    185
2020-08-30    185
2020-08-31    185
Name: CountryCode, Length: 244, dtype: int64

In [8]:
# Ensure completeness
government_regulation_df.count()

CountryName                              58804
CountryCode                              58804
RegionName                               13664
RegionCode                               13664
C1_School closing                        57041
C1_Flag                                  36138
C2_Workplace closing                     56917
C2_Flag                                  33858
C3_Cancel public events                  56984
C3_Flag                                  36934
C4_Restrictions on gatherings            56951
C4_Flag                                  33946
C5_Close public transport                57109
C5_Flag                                  21731
C6_Stay at home requirements             56951
C6_Flag                                  30450
C7_Restrictions on internal movement     57063
C7_Flag                                  29989
C8_International travel controls         56963
E1_Income support                        56011
E1_Flag                                  28012
E2_Debt/contract relief                  55582
E3_Fiscal measures                       46405
E4_International support                 46599
H1_Public information campaigns          56505
H1_Flag                                  45744
H2_Testing policy                        56161
H3_Contact tracing                       56133
H4_Emergency investment in healthcare    45914
H5_Investment in vaccines                46317
M1_Wildcard                                  0
ConfirmedCases                           46187
ConfirmedDeaths                          46187
StringencyIndex                          56848
StringencyIndexForDisplay                57702
StringencyLegacyIndex                    56888
StringencyLegacyIndexForDisplay          57742
GovernmentResponseIndex                  55872
GovernmentResponseIndexForDisplay        56725
ContainmentHealthIndex                   56109
ContainmentHealthIndexForDisplay         56962
EconomicSupportIndex                     55470
EconomicSupportIndexForDisplay           56275
Date_updated                             58804
dtype: int64

In [9]:
# Drop "M1_Wildcard" column as there is no useable data
government_regulation_df = government_regulation_df.drop(["M1_Wildcard"], axis=1)

government_regulation_df.count()

CountryName                              58804
CountryCode                              58804
RegionName                               13664
RegionCode                               13664
C1_School closing                        57041
C1_Flag                                  36138
C2_Workplace closing                     56917
C2_Flag                                  33858
C3_Cancel public events                  56984
C3_Flag                                  36934
C4_Restrictions on gatherings            56951
C4_Flag                                  33946
C5_Close public transport                57109
C5_Flag                                  21731
C6_Stay at home requirements             56951
C6_Flag                                  30450
C7_Restrictions on internal movement     57063
C7_Flag                                  29989
C8_International travel controls         56963
E1_Income support                        56011
E1_Flag                                  28012
E2_Debt/contract relief                  55582
E3_Fiscal measures                       46405
E4_International support                 46599
H1_Public information campaigns          56505
H1_Flag                                  45744
H2_Testing policy                        56161
H3_Contact tracing                       56133
H4_Emergency investment in healthcare    45914
H5_Investment in vaccines                46317
ConfirmedCases                           46187
ConfirmedDeaths                          46187
StringencyIndex                          56848
StringencyIndexForDisplay                57702
StringencyLegacyIndex                    56888
StringencyLegacyIndexForDisplay          57742
GovernmentResponseIndex                  55872
GovernmentResponseIndexForDisplay        56725
ContainmentHealthIndex                   56109
ContainmentHealthIndexForDisplay         56962
EconomicSupportIndex                     55470
EconomicSupportIndexForDisplay           56275
Date_updated                             58804
dtype: int64

In [10]:
# Remove all region data
government_regulation_df['RegionName'].replace('',np.nan,inplace=True)
government_regulation_df = government_regulation_df.loc[government_regulation_df['RegionName'].isnull()]
government_regulation_df

,CountryName,CountryCode,RegionName,RegionCode,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,...,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay,Date_updated
0,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2020-01-01
1,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2020-01-02
2,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2020-01-03
3,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2020-01-04
4,Aruba,ABW,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,2020-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58799,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.56,NaN,88.1,NaN,66.03,NaN,73.48,NaN,25.0,2020-08-27
58800,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.56,NaN,88.1,NaN,66.03,NaN,73.48,NaN,25.0,2020-08-28
58801,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.56,NaN,88.1,NaN,66.03,NaN,73.48,NaN,25.0,2020-08-29
58802,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.56,NaN,88.1,NaN,66.03,NaN,73.48,NaN,25.0,2020-08-30
58803,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.56,NaN,88.1,NaN,66.03,NaN,73.48,NaN,25.0,2020-08-31

In [11]:
# Drop columns deemed redundant/not useful 
government_regulation_df = government_regulation_df.drop(['E2_Debt/contract relief',
                                                          'E3_Fiscal measures',
                                                          'E4_International support',
                                                          'H2_Testing policy', 
                                                          'H3_Contact tracing', 
                                                          'H4_Emergency investment in healthcare', 
                                                          'H5_Investment in vaccines', 
                                                          'ConfirmedCases', 
                                                          'ConfirmedDeaths', 
                                                          'StringencyIndexForDisplay', 
                                                          'StringencyLegacyIndexForDisplay', 
                                                          'GovernmentResponseIndexForDisplay',
                                                          'ContainmentHealthIndexForDisplay',
                                                          'EconomicSupportIndexForDisplay',
                                                          'RegionName',
                                                          'RegionCode'
                                                         ], axis=1)

government_regulation_df

,CountryName,CountryCode,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,C4_Flag,...,E1_Income support,E1_Flag,H1_Public information campaigns,H1_Flag,StringencyIndex,StringencyLegacyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex,Date_updated
0,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-01
1,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-02
2,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-03
3,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-04
4,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58799,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-27
58800,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-28
58801,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-29
58802,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-30
58803,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-31

In [12]:
# Drop rows based on countries not included in "covid_stats_df"
index_drop_codes = government_regulation_df[(government_regulation_df["CountryCode"] == "MAC") |
                                            (government_regulation_df["CountryCode"] == "PCN") |
                                            (government_regulation_df["CountryCode"] == "RKS") |
                                            (government_regulation_df["CountryCode"] == "SLB") |
                                            (government_regulation_df["CountryCode"] == "TKM") |
                                            (government_regulation_df["CountryCode"] == "VUT")                                      
                                           ].index

government_regulation_df.drop(index_drop_codes, inplace=True)

government_regulation_df.head(10)

,CountryName,CountryCode,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,C4_Flag,...,E1_Income support,E1_Flag,H1_Public information campaigns,H1_Flag,StringencyIndex,StringencyLegacyIndex,GovernmentResponseIndex,ContainmentHealthIndex,EconomicSupportIndex,Date_updated
0,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-01
1,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-02
2,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-03
3,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-04
4,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-05
5,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-06
6,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-07
7,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-08
8,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-09
9,Aruba,ABW,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2020-01-10

In [13]:
# Show the number of nulls in each column of government_regulations_df
government_regulation_df.isnull().sum()

CountryName                                 0
CountryCode                                 0
C1_School closing                        1128
C1_Flag                                 17121
C2_Workplace closing                     1230
C2_Flag                                 19420
C3_Cancel public events                  1166
C3_Flag                                 16463
C4_Restrictions on gatherings            1197
C4_Flag                                 17956
C5_Close public transport                1038
C5_Flag                                 27326
C6_Stay at home requirements             1199
C6_Flag                                 21974
C7_Restrictions on internal movement     1087
C7_Flag                                 22983
C8_International travel controls         1146
E1_Income support                        1890
E1_Flag                                 24740
H1_Public information campaigns          1403
H1_Flag                                  9435
StringencyIndex                          1297
StringencyLegacyIndex                    1257
GovernmentResponseIndex                  2033
ContainmentHealthIndex                   1796
EconomicSupportIndex                     2431
Date_updated                                0
dtype: int64

In [14]:
# # For all stringency Index columns (C1-8), income support and public information campaigns, make all null values = 0
# government_regulation_df['C1_School closing'].fillna(0,inplace=True)
# government_regulation_df['C1_Flag'].fillna(0,inplace=True)
# government_regulation_df['C2_Workplace closing'].fillna(0,inplace=True)
# government_regulation_df['C2_Flag'].fillna(0,inplace=True)
# government_regulation_df['C3_Cancel public events'].fillna(0,inplace=True)
# government_regulation_df['C3_Flag'].fillna(0,inplace=True)
# government_regulation_df['C4_Restrictions on gatherings'].fillna(0,inplace=True)
# government_regulation_df['C4_Flag'].fillna(0,inplace=True)
# government_regulation_df['C5_Close public transport'].fillna(0,inplace=True)
# government_regulation_df['C5_Flag'].fillna(0,inplace=True)
# government_regulation_df['C6_Stay at home requirements'].fillna(0,inplace=True)
# government_regulation_df['C6_Flag'].fillna(0,inplace=True)
# government_regulation_df['C7_Restrictions on internal movement'].fillna(0,inplace=True)
# government_regulation_df['C7_Flag'].fillna(0,inplace=True)
# government_regulation_df['C8_International travel controls'].fillna(0,inplace=True)
# government_regulation_df['E1_Income support'].fillna(0,inplace=True)
# government_regulation_df['E1_Flag'].fillna(0,inplace=True)
# government_regulation_df['H1_Public information campaigns'].fillna(0,inplace=True)
# government_regulation_df['H1_Flag'].fillna(0,inplace=True)

In [15]:
# Re-review nulls
government_regulation_df.isnull().sum()

CountryName                                 0
CountryCode                                 0
C1_School closing                        1128
C1_Flag                                 17121
C2_Workplace closing                     1230
C2_Flag                                 19420
C3_Cancel public events                  1166
C3_Flag                                 16463
C4_Restrictions on gatherings            1197
C4_Flag                                 17956
C5_Close public transport                1038
C5_Flag                                 27326
C6_Stay at home requirements             1199
C6_Flag                                 21974
C7_Restrictions on internal movement     1087
C7_Flag                                 22983
C8_International travel controls         1146
E1_Income support                        1890
E1_Flag                                 24740
H1_Public information campaigns          1403
H1_Flag                                  9435
StringencyIndex                          1297
StringencyLegacyIndex                    1257
GovernmentResponseIndex                  2033
ContainmentHealthIndex                   1796
EconomicSupportIndex                     2431
Date_updated                                0
dtype: int64

In [16]:
# Impute total_cases_updated and total_deaths_updated
CountryCodes = government_regulation_df["CountryCode"].unique()
CountryCodes

array(['ABW', 'AFG', 'AGO', 'AIA', 'ALB', 'AND', 'ARE', 'ARG', 'AUS',
       'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR',
       'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN',
       'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD',
       'COG', 'COL', 'CPV', 'CRI', 'CUB', 'CYM', 'CYP', 'CZE', 'DEU',
       'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESP',
       'EST', 'ETH', 'FIN', 'FJI', 'FLK', 'FRA', 'GAB', 'GBR', 'GEO',
       'GHA', 'GIB', 'GIN', 'GMB', 'GRC', 'GRL', 'GTM', 'GUM', 'GUY',
       'HKG', 'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IND', 'IRL', 'IRN',
       'IRQ', 'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN',
       'KGZ', 'KHM', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LKA',
       'LSO', 'LTU', 'LUX', 'LVA', 'MAR', 'MDA', 'MDG', 'MEX', 'MLI',
       'MMR', 'MNG', 'MOZ', 'MRT', 'MSR', 'MUS', 'MWI', 'MYS', 'NAM',
       'NER', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NZL', 'OMN', 'PAK',
       'PAN', 'PER', 'PHL', 'PNG', 'POL', 'PRI', 'PRT', 'PRY', 'PSE',
       'QAT', 'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SLE',
       'SLV', 'SMR', 'SOM', 'SRB', 'SSD', 'SUR', 'SVK', 'SVN', 'SWE',
       'SWZ', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TLS',
       'TTO', 'TUN', 'TUR', 'TWN', 'TZA', 'UGA', 'UKR', 'URY', 'USA',
       'UZB', 'VEN', 'VGB', 'VNM', 'YEM', 'ZAF', 'ZMB', 'ZWE'],
      dtype=object)

In [17]:
# This function returns the index of column colname of dataframe df 

def get_col_index(df,colname):
    for i,col in enumerate(df.columns):
        if col == colname:
            return i

In [18]:
# get individual StringencyIndex measures column index
c1_col = get_col_index(government_regulation_df,"C1_School closing")
c1f_col = get_col_index(government_regulation_df,"C1_Flag")
c2_col = get_col_index(government_regulation_df,"C2_Workplace closing")
c2f_col = get_col_index(government_regulation_df,"C2_Flag")
c3_col = get_col_index(government_regulation_df,"C3_Cancel public events")
c3f_col = get_col_index(government_regulation_df,"C3_Flag")
c4_col = get_col_index(government_regulation_df,"C4_Restrictions on gatherings")
c4f_col = get_col_index(government_regulation_df,"C4_Flag")
c5_col = get_col_index(government_regulation_df,"C5_Close public transport")
c5f_col = get_col_index(government_regulation_df,"C5_Flag")
c6_col = get_col_index(government_regulation_df,"C6_Stay at home requirements")
c6f_col = get_col_index(government_regulation_df,"C6_Flag")
c7_col = get_col_index(government_regulation_df,"C7_Restrictions on internal movement")
c7f_col = get_col_index(government_regulation_df,"C7_Flag")
c8_col = get_col_index(government_regulation_df,"C8_International travel controls")
e1_col = get_col_index(government_regulation_df,"E1_Income support")
e1f_col = get_col_index(government_regulation_df,"E1_Flag")
h1_col = get_col_index(government_regulation_df,"H1_Public information campaigns")
h1f_col = get_col_index(government_regulation_df,"H1_Flag")

# get StringencyIndex_updated column index
si_col = get_col_index(government_regulation_df,"StringencyIndex")

# get StringencyLegacyIndex_updated column index
sli_col = get_col_index(government_regulation_df,"StringencyLegacyIndex")

# get GovernmentResponseIndex_updated column index
gri_col = get_col_index(government_regulation_df,"GovernmentResponseIndex")

# get StringencyIndex_updated column index
chi_col = get_col_index(government_regulation_df,"ContainmentHealthIndex")

# get StringencyIndex_updated column index
esi_col = get_col_index(government_regulation_df,"EconomicSupportIndex")

In [19]:
# Impute total_cases_updated and total_deaths_updated
iso_codes = government_regulation_df["CountryCode"].unique()

# List or processed iso dataframes
df_list = []

for code in iso_codes:

    iso_df = government_regulation_df[government_regulation_df["CountryCode"]==code].copy()
    
    # print(iso_df)
    if np.isnan(iso_df.iloc[0,c1_col]):
        iso_df.iloc[0,c1_col] = 0
    iso_df["C1_School closing"] = iso_df["C1_School closing"].ffill()
    
    if np.isnan(iso_df.iloc[0,c1f_col]):
        iso_df.iloc[0,c1f_col] = 0
    iso_df["C1_Flag"] = iso_df["C1_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c2_col]):
        iso_df.iloc[0,c2_col] = 0
    iso_df["C2_Workplace closing"] = iso_df["C2_Workplace closing"].ffill()
    
    if np.isnan(iso_df.iloc[0,c2f_col]):
        iso_df.iloc[0,c2f_col] = 0
    iso_df["C2_Flag"] = iso_df["C2_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c3_col]):
        iso_df.iloc[0,c3_col] = 0
    iso_df["C3_Cancel public events"] = iso_df["C3_Cancel public events"].ffill()
    
    if np.isnan(iso_df.iloc[0,c3f_col]):
        iso_df.iloc[0,c3f_col] = 0
    iso_df["C3_Flag"] = iso_df["C3_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c4_col]):
        iso_df.iloc[0,c4_col] = 0
    iso_df["C4_Restrictions on gatherings"] = iso_df["C4_Restrictions on gatherings"].ffill()
    
    if np.isnan(iso_df.iloc[0,c4f_col]):
        iso_df.iloc[0,c4f_col] = 0
    iso_df["C4_Flag"] = iso_df["C4_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c5_col]):
        iso_df.iloc[0,c5_col] = 0
    iso_df["C5_Close public transport"] = iso_df["C5_Close public transport"].ffill()
    
    if np.isnan(iso_df.iloc[0,c5f_col]):
        iso_df.iloc[0,c5f_col] = 0
    iso_df["C5_Flag"] = iso_df["C5_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c6_col]):
        iso_df.iloc[0,c6_col] = 0
    iso_df["C6_Stay at home requirements"] = iso_df["C6_Stay at home requirements"].ffill()
    
    if np.isnan(iso_df.iloc[0,c6f_col]):
        iso_df.iloc[0,c6f_col] = 0
    iso_df["C6_Flag"] = iso_df["C6_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c7_col]):
        iso_df.iloc[0,c7_col] = 0
    iso_df["C7_Restrictions on internal movement"] = iso_df["C7_Restrictions on internal movement"].ffill()
    
    if np.isnan(iso_df.iloc[0,c7f_col]):
        iso_df.iloc[0,c7f_col] = 0
    iso_df["C7_Flag"] = iso_df["C7_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,c8_col]):
        iso_df.iloc[0,c8_col] = 0
    iso_df["C8_International travel controls"] = iso_df["C8_International travel controls"].ffill()
    
    if np.isnan(iso_df.iloc[0,e1_col]):
        iso_df.iloc[0,e1_col] = 0
    iso_df["E1_Income support"] = iso_df["E1_Income support"].ffill()
    
    if np.isnan(iso_df.iloc[0,e1f_col]):
        iso_df.iloc[0,e1f_col] = 0
    iso_df["E1_Flag"] = iso_df["E1_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,h1_col]):
        iso_df.iloc[0,h1_col] = 0
    iso_df["H1_Public information campaigns"] = iso_df["H1_Public information campaigns"].ffill()
    
    if np.isnan(iso_df.iloc[0,h1f_col]):
        iso_df.iloc[0,h1f_col] = 0
    iso_df["H1_Flag"] = iso_df["H1_Flag"].ffill()
    
    if np.isnan(iso_df.iloc[0,si_col]):
        iso_df.iloc[0,si_col] = 0
    iso_df["StringencyIndex"] = iso_df["StringencyIndex"].ffill()

    if np.isnan(iso_df.iloc[0,sli_col]):
        iso_df.iloc[0,sli_col] = 0
    iso_df["StringencyLegacyIndex"] = iso_df["StringencyLegacyIndex"].ffill()

    if np.isnan(iso_df.iloc[0,gri_col]):
        iso_df.iloc[0,gri_col] = 0
    iso_df["GovernmentResponseIndex"] = iso_df["GovernmentResponseIndex"].ffill()

    if np.isnan(iso_df.iloc[0,chi_col]):
        iso_df.iloc[0,chi_col] = 0
    iso_df["ContainmentHealthIndex"] = iso_df["ContainmentHealthIndex"].ffill()
    
    if np.isnan(iso_df.iloc[0,esi_col]):
        iso_df.iloc[0,esi_col] = 0
    iso_df["EconomicSupportIndex"] = iso_df["EconomicSupportIndex"].ffill()

    df_list.append(iso_df)

new_df = pd.DataFrame()
for df in df_list:
    new_df = new_df.append(df)

government_regulation_df = new_df.copy()

government_regulation_df.isnull().sum()

CountryName                             0
CountryCode                             0
C1_School closing                       0
C1_Flag                                 0
C2_Workplace closing                    0
C2_Flag                                 0
C3_Cancel public events                 0
C3_Flag                                 0
C4_Restrictions on gatherings           0
C4_Flag                                 0
C5_Close public transport               0
C5_Flag                                 0
C6_Stay at home requirements            0
C6_Flag                                 0
C7_Restrictions on internal movement    0
C7_Flag                                 0
C8_International travel controls        0
E1_Income support                       0
E1_Flag                                 0
H1_Public information campaigns         0
H1_Flag                                 0
StringencyIndex                         0
StringencyLegacyIndex                   0
GovernmentResponseIndex                 0
ContainmentHealthIndex                  0
EconomicSupportIndex                    0
Date_updated                            0
dtype: int64

In [20]:
government_regulation_df.rename(columns={"C1_School closing":"C1_School_closing",
                                        "C2_Workplace closing":"C2_Workplace_closing",
                                        "C3_Cancel public events":"C3_Cancel_public_events",
                                        "C4_Restrictions on gatherings":"C4_Restrictions_on_gatherings",
                                        "C5_Close public transport":"C5_Close_public_transport",
                                        "C6_Stay at home requirements":"C6_Stay_at_home_requirements",
                                        "C7_Restrictions on internal movement":"C7_Restrictions_on_internal_movement",
                                        "C8_International travel controls":"C8_International_travel_controls",
                                        "E1_Income support":"E1_Income_support",
                                        "H1_Public information campaigns":"H1_Public_information_campaigns",
                                        "StringencyIndex":"StringencyIndex_updated",
                                        "StringencyLegacyIndex":"StringencyLegacyIndex_updated",
                                        "GovernmentResponseIndex":"GovernmentResponseIndex_updated",
                                        "ContainmentHealthIndex":"ContainmentHealthIndex_updated",
                                        "EconomicSupportIndex":"EconomicSupportIndex_updated"
                                        },inplace=True)

In [21]:
government_regulation_df

,CountryName,CountryCode,C1_School_closing,C1_Flag,C2_Workplace_closing,C2_Flag,C3_Cancel_public_events,C3_Flag,C4_Restrictions_on_gatherings,C4_Flag,...,E1_Income_support,E1_Flag,H1_Public_information_campaigns,H1_Flag,StringencyIndex_updated,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,ContainmentHealthIndex_updated,EconomicSupportIndex_updated,Date_updated
0,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,2020-01-01
1,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,2020-01-02
2,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,2020-01-03
3,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,2020-01-04
4,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,2020-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58799,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,...,1.0,1.0,2.0,1.0,80.56,88.1,66.03,73.48,25.0,2020-08-27
58800,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,...,1.0,1.0,2.0,1.0,80.56,88.1,66.03,73.48,25.0,2020-08-28
58801,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,...,1.0,1.0,2.0,1.0,80.56,88.1,66.03,73.48,25.0,2020-08-29
58802,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,...,1.0,1.0,2.0,1.0,80.56,88.1,66.03,73.48,25.0,2020-08-30
58803,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,...,1.0,1.0,2.0,1.0,80.56,88.1,66.03,73.48,25.0,2020-08-31

In [22]:
# Create new column - primary_key
government_regulation_df["primary_key_response"] = government_regulation_df["CountryCode"] + government_regulation_df["Date_updated"].astype(str)

In [23]:
# Create new column - percentage change
government_regulation_df["percentage_change_stringency"] = government_regulation_df["StringencyIndex_updated"].pct_change()*100
government_regulation_df['percentage_change_stringency'].fillna(0, inplace=True)

government_regulation_df["percentage_change_GovernmentResponse"] = government_regulation_df["GovernmentResponseIndex_updated"].pct_change()*100
government_regulation_df['percentage_change_GovernmentResponse'].fillna(0, inplace=True)

government_regulation_df["percentage_change_ContainmentHealth"] = government_regulation_df["ContainmentHealthIndex_updated"].pct_change()*100
government_regulation_df['percentage_change_ContainmentHealth'].fillna(0, inplace=True)

government_regulation_df["percentage_change_EconomicSupport"] = government_regulation_df["EconomicSupportIndex_updated"].pct_change()*100
government_regulation_df['percentage_change_EconomicSupport'].fillna(0, inplace=True)

government_regulation_df = government_regulation_df[['primary_key_response',
                                                     'Date_updated',
                                                     'CountryName',
                                                     'CountryCode',
                                                     'C1_School_closing',
                                                     'C1_Flag',
                                                     'C2_Workplace_closing',
                                                     'C2_Flag',
                                                     'C3_Cancel_public_events',
                                                     'C3_Flag',
                                                     'C4_Restrictions_on_gatherings',
                                                     'C4_Flag',
                                                     'C5_Close_public_transport',
                                                     'C5_Flag',
                                                     'C6_Stay_at_home_requirements',
                                                     'C6_Flag',
                                                     'C7_Restrictions_on_internal_movement',
                                                     'C7_Flag',
                                                     'C8_International_travel_controls',
                                                     'E1_Income_support',
                                                     'E1_Flag',
                                                     'H1_Public_information_campaigns',
                                                     'H1_Flag',
                                                     'StringencyIndex_updated',
                                                     'percentage_change_stringency',
                                                     'StringencyLegacyIndex_updated',
                                                     'GovernmentResponseIndex_updated',
                                                     'percentage_change_GovernmentResponse',
                                                     'ContainmentHealthIndex_updated',
                                                     'percentage_change_ContainmentHealth',
                                                     'EconomicSupportIndex_updated',
                                                     'percentage_change_EconomicSupport'
                                                    ]]


# Replace inf with 0 
government_regulation_df.replace(np.inf, 0, inplace=True)

government_regulation_df

,primary_key_response,Date_updated,CountryName,CountryCode,C1_School_closing,C1_Flag,C2_Workplace_closing,C2_Flag,C3_Cancel_public_events,C3_Flag,...,H1_Flag,StringencyIndex_updated,percentage_change_stringency,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport
0,ABW2020-01-01,2020-01-01,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
1,ABW2020-01-02,2020-01-02,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
2,ABW2020-01-03,2020-01-03,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
3,ABW2020-01-04,2020-01-04,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
4,ABW2020-01-05,2020-01-05,Aruba,ABW,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58799,ZWE2020-08-27,2020-08-27,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,...,1.0,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
58800,ZWE2020-08-28,2020-08-28,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,...,1.0,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
58801,ZWE2020-08-29,2020-08-29,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,...,1.0,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
58802,ZWE2020-08-30,2020-08-30,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,...,1.0,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0
58803,ZWE2020-08-31,2020-08-31,Zimbabwe,ZWE,3.0,1.0,1.0,1.0,2.0,1.0,...,1.0,80.56,0.0,88.1,66.03,0.0,73.48,0.0,25.0,0.0

### Inspect and Clean: covid_stats_df

In [24]:
# Review initial DataFrame
covid_stats_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,0.0,0.0,NaN,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,0.0,0.0,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29

In [25]:
# Review data types to ensure appropriateness
covid_stats_df.dtypes

iso_code                            object
continent                           object
location                            object
date                                object
total_cases                        float64
new_cases                          float64
new_cases_smoothed                 float64
total_deaths                       float64
new_deaths                         float64
new_deaths_smoothed                float64
total_cases_per_million            float64
new_cases_per_million              float64
new_cases_smoothed_per_million     float64
total_deaths_per_million           float64
new_deaths_per_million             float64
new_deaths_smoothed_per_million    float64
new_tests                          float64
total_tests                        float64
total_tests_per_thousand           float64
new_tests_per_thousand             float64
new_tests_smoothed                 float64
new_tests_smoothed_per_thousand    float64
tests_per_case                     float64
positive_rate                      float64
tests_units                         object
stringency_index                   float64
population                         float64
population_density                 float64
median_age                         float64
aged_65_older                      float64
aged_70_older                      float64
gdp_per_capita                     float64
extreme_poverty                    float64
cardiovasc_death_rate              float64
diabetes_prevalence                float64
female_smokers                     float64
male_smokers                       float64
handwashing_facilities             float64
hospital_beds_per_thousand         float64
life_expectancy                    float64
dtype: object

In [26]:
# Change "date" format by removing "-"
covid_stats_df['date'] = covid_stats_df['date'].str.replace('-','')

# Convert "date" column to format datetime
covid_stats_df['date_updated'] = pd.to_datetime(covid_stats_df['date'].astype(str), format='%Y%m%d')

# Drop old "date" column
covid_stats_df = covid_stats_df.drop(["date"], axis=1)

covid_stats_df.head()

,iso_code,continent,location,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,date_updated
0,ABW,North America,Aruba,2.0,2.0,NaN,0.0,0.0,NaN,18.733,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,2020-03-13
1,ABW,North America,Aruba,NaN,NaN,0.286,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,2020-03-19
2,ABW,North America,Aruba,4.0,2.0,0.286,0.0,0.0,0.0,37.465,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,2020-03-20
3,ABW,North America,Aruba,NaN,NaN,0.286,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,2020-03-21
4,ABW,North America,Aruba,NaN,NaN,0.286,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,2020-03-22

In [27]:
# Re-review data types to ensure appropriateness
covid_stats_df.dtypes

iso_code                                   object
continent                                  object
location                                   object
total_cases                               float64
new_cases                                 float64
new_cases_smoothed                        float64
total_deaths                              float64
new_deaths                                float64
new_deaths_smoothed                       float64
total_cases_per_million                   float64
new_cases_per_million                     float64
new_cases_smoothed_per_million            float64
total_deaths_per_million                  float64
new_deaths_per_million                    float64
new_deaths_smoothed_per_million           float64
new_tests                                 float64
total_tests                               float64
total_tests_per_thousand                  float64
new_tests_per_thousand                    float64
new_tests_smoothed                        float64
new_tests_smoothed_per_thousand           float64
tests_per_case                            float64
positive_rate                             float64
tests_units                                object
stringency_index                          float64
population                                float64
population_density                        float64
median_age                                float64
aged_65_older                             float64
aged_70_older                             float64
gdp_per_capita                            float64
extreme_poverty                           float64
cardiovasc_death_rate                     float64
diabetes_prevalence                       float64
female_smokers                            float64
male_smokers                              float64
handwashing_facilities                    float64
hospital_beds_per_thousand                float64
life_expectancy                           float64
date_updated                       datetime64[ns]
dtype: object

In [28]:
# Verify date range - ensure only 2020 dates for analysis
covid_stats_df.groupby("date_updated")["iso_code"].nunique()

date_updated
2019-12-31     67
2020-01-01     67
2020-01-02     67
2020-01-03     67
2020-01-04     67
             ...
2020-08-27    210
2020-08-28    210
2020-08-29    210
2020-08-30    210
2020-08-31    209
Name: iso_code, Length: 245, dtype: int64

In [29]:
# Remove Dec 31, 2019 dates - not applicable within analysis of 2020 data
covid_stats_df.drop(covid_stats_df[covid_stats_df['date_updated'] == "2019-12-31"].index, inplace = True)

In [30]:
# Confirm Dec 31, 2019 date dropped
covid_stats_df.groupby("date_updated")["iso_code"].nunique()

date_updated
2020-01-01     67
2020-01-02     67
2020-01-03     67
2020-01-04     67
2020-01-05     67
             ...
2020-08-27    210
2020-08-28    210
2020-08-29    210
2020-08-30    210
2020-08-31    209
Name: iso_code, Length: 244, dtype: int64

In [31]:
# Ensure completeness
covid_stats_df.count()

iso_code                           40436
continent                          40192
location                           40680
total_cases                        40105
new_cases                          39924
new_cases_smoothed                 39210
total_deaths                       40105
new_deaths                         39924
new_deaths_smoothed                39210
total_cases_per_million            39861
new_cases_per_million              39861
new_cases_smoothed_per_million     39145
total_deaths_per_million           39861
new_deaths_per_million             39861
new_deaths_smoothed_per_million    39145
new_tests                          13112
total_tests                        13443
total_tests_per_thousand           13443
new_tests_per_thousand             13112
new_tests_smoothed                 14742
new_tests_smoothed_per_thousand    14742
tests_per_case                     13630
positive_rate                      13986
tests_units                        15497
stringency_index                   33598
population                         40436
population_density                 38627
median_age                         36325
aged_65_older                      35791
aged_70_older                      36137
gdp_per_capita                     35872
extreme_poverty                    23956
cardiovasc_death_rate              36338
diabetes_prevalence                37605
female_smokers                     28609
male_smokers                       28252
handwashing_facilities             16885
hospital_beds_per_thousand         32909
life_expectancy                    39935
date_updated                       40680
dtype: int64

In [32]:
# Drop columns deemed redundant/not useful 
covid_stats_df = covid_stats_df.drop(['new_cases_smoothed', 
                                      'new_deaths_smoothed',
                                      'total_cases_per_million',
                                      'new_cases_per_million',
                                      'new_cases_smoothed_per_million',
                                      'total_deaths_per_million',
                                      'new_deaths_per_million',
                                      'new_deaths_smoothed_per_million',
                                      'total_tests_per_thousand',
                                      'new_tests_per_thousand',
                                      'new_tests_smoothed',
                                      'new_tests_smoothed_per_thousand',
                                      'stringency_index',
                                      'aged_65_older',
                                      'aged_70_older',
                                      'gdp_per_capita',
                                      'extreme_poverty',
                                      'cardiovasc_death_rate',
                                      'diabetes_prevalence',
                                      'female_smokers',
                                      'male_smokers',
                                      'handwashing_facilities',
                                      'hospital_beds_per_thousand',
                                      'life_expectancy',
                                      'tests_per_case',
                                      'positive_rate',
                                      'tests_units'
                                     ], axis=1)

covid_stats_df

,iso_code,continent,location,total_cases,new_cases,total_deaths,new_deaths,new_tests,total_tests,population,population_density,median_age,date_updated
0,ABW,North America,Aruba,2.0,2.0,0.0,0.0,NaN,NaN,106766.0,584.8,41.2,2020-03-13
1,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,106766.0,584.8,41.2,2020-03-19
2,ABW,North America,Aruba,4.0,2.0,0.0,0.0,NaN,NaN,106766.0,584.8,41.2,2020-03-20
3,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,106766.0,584.8,41.2,2020-03-21
4,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,106766.0,584.8,41.2,2020-03-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40743,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-27
40744,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-28
40745,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-29
40746,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-30
40747,NaN,NaN,International,696.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-08-31

In [33]:
# Drop rows based on countries not included in "government_regulation_df"
index_drop_codes = covid_stats_df[(covid_stats_df['iso_code'] == 'ARM') |
                                  (covid_stats_df['iso_code'] == 'ATG') |
                                  (covid_stats_df['iso_code'] == 'BES') |
                                  (covid_stats_df['iso_code'] == 'BHS') |
                                  (covid_stats_df['iso_code'] == 'COM') |
                                  (covid_stats_df['iso_code'] == 'CUW') |
                                  (covid_stats_df['iso_code'] == 'ESH') |
                                  (covid_stats_df['iso_code'] == 'FRO') | 
                                  (covid_stats_df['iso_code'] == 'GGY') |
                                  (covid_stats_df['iso_code'] == 'GNB') |
                                  (covid_stats_df['iso_code'] == 'GNQ') |
                                  (covid_stats_df['iso_code'] == 'GRD') |
                                  (covid_stats_df['iso_code'] == 'IMN') |
                                  (covid_stats_df['iso_code'] == 'JEY') |
                                  (covid_stats_df['iso_code'] == 'KNA') |
                                  (covid_stats_df['iso_code'] == 'LCA') |
                                  (covid_stats_df['iso_code'] == 'LIE') |
                                  (covid_stats_df['iso_code'] == 'MCO') |
                                  (covid_stats_df['iso_code'] == 'MDV') |
                                  (covid_stats_df['iso_code'] == 'MKD') |
                                  (covid_stats_df['iso_code'] == 'MLT') |
                                  (covid_stats_df['iso_code'] == 'MNE') |
                                  (covid_stats_df['iso_code'] == 'MNP') |
                                  (covid_stats_df['iso_code'] == 'NCL') |
                                  (covid_stats_df['iso_code'] == 'OWID_KOS') |
                                  (covid_stats_df['iso_code'] == 'OWID_WRL') |
                                  (covid_stats_df['iso_code'] == 'PYF') |
                                  (covid_stats_df['iso_code'] == 'STP') |
                                  (covid_stats_df['iso_code'] == 'SXM') |
                                  (covid_stats_df['iso_code'] == 'VAT') |
                                  (covid_stats_df['iso_code'] == 'VCT') |
                                  (covid_stats_df['iso_code'] == 'VIR') |
                                  (covid_stats_df['location'] == 'International')
                                 ].index

covid_stats_df.drop(index_drop_codes, inplace=True)

covid_stats_df

,iso_code,continent,location,total_cases,new_cases,total_deaths,new_deaths,new_tests,total_tests,population,population_density,median_age,date_updated
0,ABW,North America,Aruba,2.0,2.0,0.0,0.0,NaN,NaN,106766.0,584.800,41.2,2020-03-13
1,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,106766.0,584.800,41.2,2020-03-19
2,ABW,North America,Aruba,4.0,2.0,0.0,0.0,NaN,NaN,106766.0,584.800,41.2,2020-03-20
3,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,106766.0,584.800,41.2,2020-03-21
4,ABW,North America,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,106766.0,584.800,41.2,2020-03-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40253,ZWE,Africa,Zimbabwe,6251.0,55.0,179.0,13.0,951.0,95721.0,14862927.0,42.729,19.6,2020-08-27
40254,ZWE,Africa,Zimbabwe,6292.0,41.0,189.0,10.0,1551.0,97272.0,14862927.0,42.729,19.6,2020-08-28
40255,ZWE,Africa,Zimbabwe,6388.0,96.0,195.0,6.0,NaN,NaN,14862927.0,42.729,19.6,2020-08-29
40256,ZWE,Africa,Zimbabwe,6406.0,18.0,196.0,1.0,NaN,NaN,14862927.0,42.729,19.6,2020-08-30
40257,ZWE,Africa,Zimbabwe,6412.0,6.0,196.0,0.0,NaN,NaN,14862927.0,42.729,19.6,2020-08-31

In [34]:
# In all "new" columns, replace NaN with 0 
covid_stats_df['new_cases'].fillna(0, inplace=True)
covid_stats_df['new_deaths'].fillna(0, inplace=True)
covid_stats_df['new_tests'].fillna(0, inplace=True)
covid_stats_df

,iso_code,continent,location,total_cases,new_cases,total_deaths,new_deaths,new_tests,total_tests,population,population_density,median_age,date_updated
0,ABW,North America,Aruba,2.0,2.0,0.0,0.0,0.0,NaN,106766.0,584.800,41.2,2020-03-13
1,ABW,North America,Aruba,NaN,0.0,NaN,0.0,0.0,NaN,106766.0,584.800,41.2,2020-03-19
2,ABW,North America,Aruba,4.0,2.0,0.0,0.0,0.0,NaN,106766.0,584.800,41.2,2020-03-20
3,ABW,North America,Aruba,NaN,0.0,NaN,0.0,0.0,NaN,106766.0,584.800,41.2,2020-03-21
4,ABW,North America,Aruba,NaN,0.0,NaN,0.0,0.0,NaN,106766.0,584.800,41.2,2020-03-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40253,ZWE,Africa,Zimbabwe,6251.0,55.0,179.0,13.0,951.0,95721.0,14862927.0,42.729,19.6,2020-08-27
40254,ZWE,Africa,Zimbabwe,6292.0,41.0,189.0,10.0,1551.0,97272.0,14862927.0,42.729,19.6,2020-08-28
40255,ZWE,Africa,Zimbabwe,6388.0,96.0,195.0,6.0,0.0,NaN,14862927.0,42.729,19.6,2020-08-29
40256,ZWE,Africa,Zimbabwe,6406.0,18.0,196.0,1.0,0.0,NaN,14862927.0,42.729,19.6,2020-08-30
40257,ZWE,Africa,Zimbabwe,6412.0,6.0,196.0,0.0,0.0,NaN,14862927.0,42.729,19.6,2020-08-31

## Handle nulls in total_cases,total_deaths, and total_tests

In [35]:
# Impute total_cases_updated and total_deaths_updated
iso_codes = covid_stats_df["iso_code"].unique()

# get total_cases_updated column index
tc_col = get_col_index(covid_stats_df,"total_cases")

# get total_deaths_updated column index
td_col = get_col_index(covid_stats_df,"total_deaths")

# get new_cases column index
nc_col = get_col_index(covid_stats_df,"new_cases")

# get new_deaths column index
nd_col = get_col_index(covid_stats_df,"new_deaths")

# get new_tests column index
nt_col = get_col_index(covid_stats_df,"new_tests")

# get total_tests column index
tt_col = get_col_index(covid_stats_df,"total_tests")

In [36]:
# Impute total_cases_updated and total_deaths_updated
iso_codes = covid_stats_df["iso_code"].unique()

# List or processed iso dataframes
df_list = []

for code in iso_codes:

    iso_df = covid_stats_df[covid_stats_df["iso_code"]==code].copy()
    if np.isnan(iso_df.iloc[0,tc_col]):
        iso_df.iloc[0,tc_col] = iso_df.iloc[0,nc_col]
    iso_df["total_cases"] = iso_df["total_cases"].ffill()

    if np.isnan(iso_df.iloc[0,td_col]):
        iso_df.iloc[0,td_col] = iso_df.iloc[0,nd_col]
    iso_df["total_deaths"] = iso_df["total_deaths"].ffill()

    if np.isnan(iso_df.iloc[0,tt_col]):
        iso_df.iloc[0,tt_col] = iso_df.iloc[0,nt_col]
    iso_df["total_tests"] = iso_df["total_tests"].ffill()

    df_list.append(iso_df)

new_df = pd.DataFrame()
for df in df_list:
    new_df = new_df.append(df)

covid_stats_df = new_df.copy()

covid_stats_df.isnull().sum()

iso_code                 0
continent                0
location                 0
total_cases              0
new_cases                0
total_deaths             0
new_deaths               0
new_tests                0
total_tests              0
population               0
population_density    1026
median_age            2033
date_updated             0
dtype: int64

In [37]:
# Add _updated suffix to new and total column names

cols = ["total_cases","total_deaths","total_tests"]
dct = {col:"_".join([col,"updated"]) for col in cols}
covid_stats_df.rename(columns=dct,inplace=True)
covid_stats_df.columns

Index(['iso_code', 'continent', 'location', 'total_cases_updated', 'new_cases',
       'total_deaths_updated', 'new_deaths', 'new_tests',
       'total_tests_updated', 'population', 'population_density', 'median_age',
       'date_updated'],
      dtype='object')

## Handle nulls in population_density

In [38]:
# Find Countries with null population_density

population_density_nulls_iso = covid_stats_df[covid_stats_df["population_density"].isnull()]["iso_code"].unique()

for iso_code in population_density_nulls_iso:
    iso_df = covid_stats_df[covid_stats_df["iso_code"]==iso_code]
    print(f"{iso_code}: rows = {iso_df.shape[0]}, rows_null_population_density: {iso_df['population_density'].isnull().sum()}")

AIA: rows = 158, rows_null_population_density: 158
FLK: rows = 150, rows_null_population_density: 150
MSR: rows = 164, rows_null_population_density: 164
SSD: rows = 148, rows_null_population_density: 148
SYR: rows = 162, rows_null_population_density: 162
TWN: rows = 244, rows_null_population_density: 244

In [39]:
# Drop all countries with missing population_density

null_population_density_index = covid_stats_df[covid_stats_df["iso_code"].isin(population_density_nulls_iso)].index
covid_stats_df.drop(null_population_density_index, inplace=True)

covid_stats_df.isnull().sum()

iso_code                   0
continent                  0
location                   0
total_cases_updated        0
new_cases                  0
total_deaths_updated       0
new_deaths                 0
new_tests                  0
total_tests_updated        0
population                 0
population_density         0
median_age              1561
date_updated               0
dtype: int64

## Handle nulls in median_age

In [40]:
# Find Countries with null median_age
null_median_age_index = covid_stats_df[covid_stats_df["median_age"].isnull()].index

median_age_nulls_iso = covid_stats_df[covid_stats_df["median_age"].isnull()]["iso_code"].unique()

for iso_code in median_age_nulls_iso:
    iso_df = covid_stats_df[covid_stats_df["iso_code"]==iso_code]
    print(f"{iso_code}: rows = {iso_df.shape[0]}, rows_null_median_age: {iso_df['median_age'].isnull().sum()}")

AND: rows = 177, rows_null_median_age: 177
BMU: rows = 165, rows_null_median_age: 165
CYM: rows = 165, rows_null_median_age: 165
DMA: rows = 162, rows_null_median_age: 162
GIB: rows = 165, rows_null_median_age: 165
GRL: rows = 165, rows_null_median_age: 165
SMR: rows = 244, rows_null_median_age: 244
TCA: rows = 160, rows_null_median_age: 160
VGB: rows = 158, rows_null_median_age: 158

In [41]:
# Drop all countries with missing median_age

null_median_age_index = covid_stats_df[covid_stats_df["iso_code"].isin(median_age_nulls_iso)].index
covid_stats_df.drop(null_median_age_index, inplace=True)

covid_stats_df.isnull().sum()

iso_code                0
continent               0
location                0
total_cases_updated     0
new_cases               0
total_deaths_updated    0
new_deaths              0
new_tests               0
total_tests_updated     0
population              0
population_density      0
median_age              0
date_updated            0
dtype: int64

In [42]:
# It was discovered that for some countries there are is not any data on testing, will replace NaN with 0
covid_stats_df['total_tests_updated'].fillna(0, inplace=True)
covid_stats_df

,iso_code,continent,location,total_cases_updated,new_cases,total_deaths_updated,new_deaths,new_tests,total_tests_updated,population,population_density,median_age,date_updated
0,ABW,North America,Aruba,2.0,2.0,0.0,0.0,0.0,0.0,106766.0,584.800,41.2,2020-03-13
1,ABW,North America,Aruba,2.0,0.0,0.0,0.0,0.0,0.0,106766.0,584.800,41.2,2020-03-19
2,ABW,North America,Aruba,4.0,2.0,0.0,0.0,0.0,0.0,106766.0,584.800,41.2,2020-03-20
3,ABW,North America,Aruba,4.0,0.0,0.0,0.0,0.0,0.0,106766.0,584.800,41.2,2020-03-21
4,ABW,North America,Aruba,4.0,0.0,0.0,0.0,0.0,0.0,106766.0,584.800,41.2,2020-03-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40253,ZWE,Africa,Zimbabwe,6251.0,55.0,179.0,13.0,951.0,95721.0,14862927.0,42.729,19.6,2020-08-27
40254,ZWE,Africa,Zimbabwe,6292.0,41.0,189.0,10.0,1551.0,97272.0,14862927.0,42.729,19.6,2020-08-28
40255,ZWE,Africa,Zimbabwe,6388.0,96.0,195.0,6.0,0.0,97272.0,14862927.0,42.729,19.6,2020-08-29
40256,ZWE,Africa,Zimbabwe,6406.0,18.0,196.0,1.0,0.0,97272.0,14862927.0,42.729,19.6,2020-08-30
40257,ZWE,Africa,Zimbabwe,6412.0,6.0,196.0,0.0,0.0,97272.0,14862927.0,42.729,19.6,2020-08-31

In [43]:
# For all new and total columns
covid_stats_df['percentage_of_Pop_New_Tests'] = (covid_stats_df['new_tests']/covid_stats_df['population'])*100
covid_stats_df['percentage_of_Pop_Total_Tests'] = (covid_stats_df['total_tests_updated']/covid_stats_df['population'])*100

covid_stats_df['percentage_of_Pop_New_Cases'] = (covid_stats_df['new_cases']/covid_stats_df['population'])*100
covid_stats_df['percentage_of_Pop_Total_Cases'] = (covid_stats_df['total_cases_updated']/covid_stats_df['population'])*100

covid_stats_df['percentage_of_Pop_New_Deaths'] = (covid_stats_df['new_deaths']/covid_stats_df['population'])
covid_stats_df['percentage_of_Pop_Total_Deaths'] = (covid_stats_df['total_deaths_updated']/covid_stats_df['population'])*100

covid_stats_df["primary_key_reaction"] = covid_stats_df["iso_code"] + covid_stats_df["date_updated"].astype(str)

covid_stats_df = covid_stats_df[['primary_key_reaction',
                                       'date_updated',
                                       'iso_code',
                                       'continent',
                                       'location',
                                       'population',
                                       'population_density',
                                       'median_age',
                                       'new_cases',
                                       'percentage_of_Pop_New_Cases',
                                       'new_deaths',
                                       'percentage_of_Pop_New_Deaths',
                                       'new_tests',
                                       'percentage_of_Pop_New_Tests',
                                       'total_cases_updated',
                                       'percentage_of_Pop_Total_Cases',
                                       'total_deaths_updated',
                                       'percentage_of_Pop_Total_Deaths',
                                       'total_tests_updated',
                                       'percentage_of_Pop_Total_Tests'
                                       ]]

# Replace inf with 0 
covid_stats_df.replace(np.inf, 0, inplace=True)

covid_stats_df.tail()

,primary_key_reaction,date_updated,iso_code,continent,location,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,new_deaths,percentage_of_Pop_New_Deaths,new_tests,percentage_of_Pop_New_Tests,total_cases_updated,percentage_of_Pop_Total_Cases,total_deaths_updated,percentage_of_Pop_Total_Deaths,total_tests_updated,percentage_of_Pop_Total_Tests
40253,ZWE2020-08-27,2020-08-27,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,55.0,0.000370,13.0,8.746595e-07,951.0,0.006398,6251.0,0.042058,179.0,0.001204,95721.0,0.644025
40254,ZWE2020-08-28,2020-08-28,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,41.0,0.000276,10.0,6.728150e-07,1551.0,0.010435,6292.0,0.042334,189.0,0.001272,97272.0,0.654461
40255,ZWE2020-08-29,2020-08-29,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,96.0,0.000646,6.0,4.036890e-07,0.0,0.000000,6388.0,0.042979,195.0,0.001312,97272.0,0.654461
40256,ZWE2020-08-30,2020-08-30,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,18.0,0.000121,1.0,6.728150e-08,0.0,0.000000,6406.0,0.043101,196.0,0.001319,97272.0,0.654461
40257,ZWE2020-08-31,2020-08-31,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,6.0,0.000040,0.0,0.000000e+00,0.0,0.000000,6412.0,0.043141,196.0,0.001319,97272.0,0.654461

### Merge and Export

In [44]:
# Merge both DataFrames, drop redundant columns
merged_covid_df = pd.merge(covid_stats_df,government_regulation_df, how="inner", left_on=['primary_key_reaction'], right_on=['primary_key_response'])
merged_covid_df.drop(['Date_updated','CountryName','CountryCode'],axis=1,inplace=True)
merged_covid_df

,primary_key_reaction,date_updated,iso_code,continent,location,population,population_density,median_age,new_cases,percentage_of_Pop_New_Cases,...,H1_Flag,StringencyIndex_updated,percentage_change_stringency,StringencyLegacyIndex_updated,GovernmentResponseIndex_updated,percentage_change_GovernmentResponse,ContainmentHealthIndex_updated,percentage_change_ContainmentHealth,EconomicSupportIndex_updated,percentage_change_EconomicSupport
0,ABW2020-03-13,2020-03-13,ABW,North America,Aruba,106766.0,584.800,41.2,2.0,0.001873,...,0.0,0.00,0.000000,0.00,2.56,0.000000,3.03,0.000000,0.0,0.0
1,ABW2020-03-19,2020-03-19,ABW,North America,Aruba,106766.0,584.800,41.2,0.0,0.000000,...,1.0,33.33,0.000000,42.86,29.49,15.015601,34.85,15.016502,0.0,0.0
2,ABW2020-03-20,2020-03-20,ABW,North America,Aruba,106766.0,584.800,41.2,2.0,0.001873,...,1.0,33.33,0.000000,42.86,29.49,0.000000,34.85,0.000000,0.0,0.0
3,ABW2020-03-21,2020-03-21,ABW,North America,Aruba,106766.0,584.800,41.2,0.0,0.000000,...,1.0,44.44,33.333333,60.71,37.18,26.076636,43.94,26.083214,0.0,0.0
4,ABW2020-03-22,2020-03-22,ABW,North America,Aruba,106766.0,584.800,41.2,0.0,0.000000,...,1.0,44.44,0.000000,60.71,37.18,0.000000,43.94,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32272,ZWE2020-08-27,2020-08-27,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,55.0,0.000370,...,1.0,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32273,ZWE2020-08-28,2020-08-28,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,41.0,0.000276,...,1.0,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32274,ZWE2020-08-29,2020-08-29,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,96.0,0.000646,...,1.0,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32275,ZWE2020-08-30,2020-08-30,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,18.0,0.000121,...,1.0,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0
32276,ZWE2020-08-31,2020-08-31,ZWE,Africa,Zimbabwe,14862927.0,42.729,19.6,6.0,0.000040,...,1.0,80.56,0.000000,88.10,66.03,0.000000,73.48,0.000000,25.0,0.0

In [45]:
# Export all three DataFrames to .csv
merged_covid_df.to_csv('Resources/merged_covid_FINAL.csv', index=False)
covid_stats_df.to_csv('Resources/covid_stats_FINAL.csv', index=False)
government_regulation_df.to_csv('Resources/government_regulation_FINAL.csv', index=False)

### the end :)